---
recipe_app:
  args:
    store: recipe
    url_root: /recipe
    tag_text:
        $config: tags.yml
  class: Statocles::App::Blog

deploy:
  args:
    remote: deploy
    branch: deploy
  class: Statocles::Deploy::Git

page_app:
  args:
    store: page
    url_root: /page
  class: Statocles::App::Plain

site:
  args:
    base_url: http://indiepalate.com
    data:
        google_analytics_id: 'UA-61295159-1'
    apps:
      recipe:
        $ref: recipe_app
      kitchen:
        $ref: kitchen_log
      page:
        $ref: page_app
      images:
        $ref: images_app
    deploy:
      $ref: deploy
    index: /recipe
    nav:
      main:
        - href: /
          title: Recipes
        - href: /kitchen
          title: Kitchen
    theme:
      $ref: theme
    title: Indie Palate
  class: Statocles::Site
  on:
    - build:
        $class: Statocles::Plugin::LinkCheck
        $sub: check_pages

images_app:
  args:
    store: images
    url_root: /images
  class: Statocles::App::Static

theme:
  args:
    store: theme
  class: Statocles::Theme

kitchen_log:
  args:
    store: kitchen
    url_root: /kitchen
  class: Statocles::App::Blog
