---
blog_app:
    class: Statocles::App::Blog
    args:
        store: blog
        url_root: /blog
        tag_text:
            $config: tags.yml

recipe_app:
  args:
    store: recipe
    url_root: /recipe
  class: Statocles::App::Basic

deploy:
  args:
    remote: deploy
    branch: deploy
  class: Statocles::Deploy::Git

pantry_app:
  args:
    store: pantry
    url_root: /pantry
  class: Statocles::App::Basic

site:
  args:
    base_url: http://indiepalate.com
    data:
        google_analytics_id: 'UA-61295159-1'
        disqus:
            shortname: indiepalate
    apps:
      recipe:
        $ref: recipe_app
      blog:
        $ref: blog_app
      pantry:
        $ref: pantry_app
      root:
        $ref: page_app
    deploy:
      $ref: deploy
    index: /blog
    nav:
      main:
        - href: /
          title: Blog
        - href: /blog/tag/recipe
          title: Recipes
    theme:
      $ref: theme
    title: Indie Palate
  class: Statocles::Site
  on:
    - build:
        $class: Statocles::Plugin::LinkCheck
        $sub: check_pages

page_app:
  args:
    store: page
    url_root: /page
  class: Statocles::App::Basic

theme:
  args:
    store: theme
  class: Statocles::Theme
