---
blog_app:
  args:
    store: blog
    url_root: /blog
  class: Statocles::App::Blog

deploy:
  args:
    remote: deploy
    branch: deploy
  class: Statocles::Deploy::Git

page_app:
  args:
    store: page
    url_root: /page
  class: Statocles::App::Plain

site:
  args:
    base_url: http://indiepalate.com
    apps:
      blog:
        $ref: blog_app
      page:
        $ref: page_app
      static:
        $ref: static_app
      images:
        $ref: images_app
    deploy:
      $ref: deploy
    index: blog
    nav:
      main:
        - href: /
          title: Blog
    theme:
      $ref: theme
    title: Indie(scriminate) Palate
  class: Statocles::Site

static_app:
  args:
    store: static
    url_root: /static
  class: Statocles::App::Static

images_app:
  args:
    store: images
    url_root: /images
  class: Statocles::App::Static

theme:
  args:
    store: theme
  class: Statocles::Theme
